/*
*
* SPDX-License-Identifier: GPL-2.0
*
* Copyright (C) 2011-2021 ARM or its affiliates
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2.
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*
*/

#if !defined( __DUMMY_SENSOR_H__ )
#define __DUMMY_SENSOR_H__

/*-----------------------------------------------------------------------------
Generated by Sensor Sequence compiler (seq_compile_source.py) - do not edit
-----------------------------------------------------------------------------*/

#include "sensor_init.h"

static const sensor_reg_t seq_table[] = {
    // Start_idx 0, size 4
    // Group 0 seq1
    {0xFFFF, 20}, // Wait command - address is 0xFFFF

    {0xFFFF, 0}, // Wait command - address is 0xFFFF

    {0xaa56, 0xdead},
    {0xaa58, 0xbeef},
    {0x0000, 0x0000}, // Stop sequence - address is 0x0000

    // Start_idx 4, size 6
    // Group 1 seq1plus
    {0xFFFF, 20}, // Wait command - address is 0xFFFF

    {0xFFFF, 0}, // Wait command - address is 0xFFFF

    {0xaa56, 0xdead},
    {0xaa58, 0xbeef},

    {0xaa0c, 0xdead},
    {0xaa30, 0xbeef},
    {0x0000, 0x0000}, // Stop sequence - address is 0x0000


};


#define SENSOR_DUMMY_SEQUENCE_DEFAULT seq_table
#define SENSOR_DUMMY_SEQUENCE_DEFAULT_SEQ1 0
#define SENSOR_DUMMY_SEQUENCE_DEFAULT_SEQ1PLUS 5

#endif /* __DUMMY_SENSOR_H__ */
