# SPDX-License-Identifier: GPL-2.0-only
simaai_pep_drv-objs	:= \
	simaai_pep_drv_common.o \
	simaai_pep_net_drv.o \
	simaai_pep_drv_modalix.o \
	simaai_pep_drv_davinci.o

obj-$(CONFIG_SIMAAI_PCIE_EP)	+= simaai_pep_drv.o
