# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_CSI_VIDEO_PLATFORM) += csi_video_plat.o
obj-$(CONFIG_DWC_MIPI_CSI2_HOST) += dw_mipi_csi.o
obj-$(CONFIG_CSI_VIDEO_DEVICE)   += csi_video_device.o
obj-$(CONFIG_DWC_MIPI_DPHY_GEN3) += dw-dphy-platfrm.o
dw-dphy-platfrm-objs := dw-dphy-plat.o dw-dphy-rx.o
