/*
*
* SPDX-License-Identifier: GPL-2.0
*
* Copyright (C) 2011-2021 ARM or its affiliates
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2.
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*
*/

// File generated by gen_global_settings.py
#ifndef __ACAMERA_SETTINGS_H__
#define __ACAMERA_SETTINGS_H__

#include "sensor_api.h"

typedef struct context_options_t {
    uint8_t cmd_if_is_passive_mode;
} context_options_t;

typedef struct _acamera_settings {
    // Sensor related setting for the context
    char *sensor_name; // Sensor name string

    void ( *sensor_init )( void **priv_ptr,
                           uint8_t location,
                           sensor_control_t *ctrl,
                           const sensor_options_t *const options ); // Function ptr to initialize sensor

    sensor_options_t sensor_options; // Sensor options

    // Context calibration / register settings
    int32_t ( *get_calibrations )( uint32_t wdr_mode, void *param ); // Function ptr to get calibration

    context_options_t context_options; // Context options

    // Other configurations
    int32_t isp_base; // ISP context CDMA offset from memory start address
} acamera_settings;


#endif // __ACAMERA_SETTINGS_H__
