# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# SiMa.ai processors
#
# Copyright (c) 2021 SiMa ai
#

dtb-$(CONFIG_ARCH_SIMAAI) += davinci-combo-board.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += davinci-dual-m2.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += davinci-hhhl.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-emulation-bench.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-dvt.dtb
