# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# SiMa.ai processors
#
# Copyright (c) 2025 SiMa ai
#

dtb-$(CONFIG_ARCH_SIMAAI) += davinci-combo-board.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += davinci-dual-m2.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += davinci-hhhl.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-dvt.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-hhhl.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-hhhl_1r.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-hhhl_x16.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-hhhl_v2.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-som.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-som_8g.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-vdk.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-zebu-basic.dtb
dtb-$(CONFIG_ARCH_SIMAAI) += modalix-zebu-pcie.dtb
