# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for SiMa.ai CSI-2 platform

obj-$(CONFIG_VIDEO_DWC_MIPI_CSI2) += dwc-mipi-csi2.o
obj-$(CONFIG_SIMAAI_V4L2_VIDEO)	+= simaai-v4l2-video.o
obj-$(CONFIG_SIMAAI_V4L2_VDMA)	+= simaai-v4l2-vdma.o
