/*
*
* SPDX-License-Identifier: GPL-2.0
*
* Copyright (C) 2011-2021 ARM or its affiliates
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; version 2.
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
* You should have received a copy of the GNU General Public License along
* with this program; if not, write to the Free Software Foundation, Inc.,
* 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*
*/

#include "context_params.h"
#include "isp_params.h"

// Map API command id to param id
#define COMMAND_TO_PARAM_MAP_MAX_ID 0x00000064

static uint32_t command_to_param_map[COMMAND_TO_PARAM_MAP_MAX_ID + 1] = {
    FW_REVISION_PARAM,                             // FW_REVISION
    CONTEXT_NUMBER_PARAM,                          // CONTEXT_NUMBER
    ACTIVE_CONTEXT_PARAM,                          // ACTIVE_CONTEXT
    SENSOR_SUPPORTED_PRESETS_PARAM,                // SENSOR_SUPPORTED_PRESETS
    SENSOR_PRESET_PARAM,                           // SENSOR_PRESET
    SENSOR_WDR_MODE_PARAM,                         // SENSOR_WDR_MODE
    SENSOR_STREAMING_PARAM,                        // SENSOR_STREAMING
    SENSOR_EXPOSURES_PARAM,                        // SENSOR_EXPOSURES
    SENSOR_FPS_PARAM,                              // SENSOR_FPS
    SENSOR_WIDTH_PARAM,                            // SENSOR_WIDTH
    SENSOR_HEIGHT_PARAM,                           // SENSOR_HEIGHT
    SENSOR_INFO_PRESET_PARAM,                      // SENSOR_INFO_PRESET
    SENSOR_INFO_WDR_MODE_PARAM,                    // SENSOR_INFO_WDR_MODE
    SENSOR_INFO_FPS_PARAM,                         // SENSOR_INFO_FPS
    SENSOR_INFO_WIDTH_PARAM,                       // SENSOR_INFO_WIDTH
    SENSOR_INFO_HEIGHT_PARAM,                      // SENSOR_INFO_HEIGHT
    SENSOR_INFO_EXPOSURES_PARAM,                   // SENSOR_INFO_EXPOSURES
    SENSOR_INFO_CHANNELS_PARAM,                    // SENSOR_INFO_CHANNELS
    SENSOR_INFO_DATA_WIDTH_PARAM,                  // SENSOR_INFO_DATA_WIDTH
    SENSOR_INTEGRATION_TIME_MIN_PARAM,             // SENSOR_INTEGRATION_TIME_MIN
    SENSOR_INTEGRATION_TIME_LIMIT_PARAM,           // SENSOR_INTEGRATION_TIME_LIMIT
    SYSTEM_LOGGER_LEVEL_PARAM,                     // SYSTEM_LOGGER_LEVEL
    SYSTEM_LOGGER_MASK_PARAM,                      // SYSTEM_LOGGER_MASK
    MCFE_USECASE_PARAM,                            // MCFE_USECASE
    CONTEXT_STATE_PARAM,                           // CONTEXT_STATE
    CMD_INTERFACE_MODE_PARAM,                      // CMD_INTERFACE_MODE
    V4L2_INTERFACE_MODE_PARAM,                     // V4L2_INTERFACE_MODE
    M2M_PROCESS_REQUEST_PARAM,                     // M2M_PROCESS_REQUEST
    BUFFER_DATA_TYPE_PARAM,                        // BUFFER_DATA_TYPE
    TEST_PATTERN_ENABLE_ID_PARAM,                  // TEST_PATTERN_ENABLE_ID
    TEST_PATTERN_MODE_ID_PARAM,                    // TEST_PATTERN_MODE_ID
    SYSTEM_FREEZE_FIRMWARE_PARAM,                  // SYSTEM_FREEZE_FIRMWARE
    SYSTEM_MANUAL_EXPOSURE_PARAM,                  // SYSTEM_MANUAL_EXPOSURE
    SYSTEM_MANUAL_MAX_INTEGRATION_TIME_PARAM,      // SYSTEM_MANUAL_MAX_INTEGRATION_TIME
    SYSTEM_MANUAL_EXPOSURE_RATIO_PARAM,            // SYSTEM_MANUAL_EXPOSURE_RATIO
    SYSTEM_MANUAL_INTEGRATION_TIME_PARAM,          // SYSTEM_MANUAL_INTEGRATION_TIME
    SYSTEM_MANUAL_SENSOR_ANALOG_GAIN_PARAM,        // SYSTEM_MANUAL_SENSOR_ANALOG_GAIN
    SYSTEM_MANUAL_SENSOR_DIGITAL_GAIN_PARAM,       // SYSTEM_MANUAL_SENSOR_DIGITAL_GAIN
    SYSTEM_MANUAL_ISP_DIGITAL_GAIN_PARAM,          // SYSTEM_MANUAL_ISP_DIGITAL_GAIN
    SYSTEM_MANUAL_DIRECTIONAL_SHARPENING_PARAM,    // SYSTEM_MANUAL_DIRECTIONAL_SHARPENING
    SYSTEM_MANUAL_UN_DIRECTIONAL_SHARPENING_PARAM, // SYSTEM_MANUAL_UN_DIRECTIONAL_SHARPENING
    SYSTEM_MANUAL_AWB_PARAM,                       // SYSTEM_MANUAL_AWB
    SYSTEM_ANTIFLICKER_ENABLE_PARAM,               // SYSTEM_ANTIFLICKER_ENABLE
    SYSTEM_MANUAL_SATURATION_PARAM,                // SYSTEM_MANUAL_SATURATION
    SYSTEM_EXPOSURE_PARAM,                         // SYSTEM_EXPOSURE
    SYSTEM_INTEGRATION_TIME_PRECISION_PARAM,       // SYSTEM_INTEGRATION_TIME_PRECISION
    SYSTEM_EXPOSURE_RATIO_PARAM,                   // SYSTEM_EXPOSURE_RATIO
    SYSTEM_MAX_EXPOSURE_RATIO_PARAM,               // SYSTEM_MAX_EXPOSURE_RATIO
    SYSTEM_INTEGRATION_TIME_PARAM,                 // SYSTEM_INTEGRATION_TIME
    SYSTEM_LONG_INTEGRATION_TIME_PARAM,            // SYSTEM_LONG_INTEGRATION_TIME
    SYSTEM_MIDDLE2_INTEGRATION_TIME_PARAM,         // SYSTEM_MIDDLE2_INTEGRATION_TIME
    SYSTEM_MIDDLE_INTEGRATION_TIME_PARAM,          // SYSTEM_MIDDLE_INTEGRATION_TIME
    SYSTEM_SHORT_INTEGRATION_TIME_PARAM,           // SYSTEM_SHORT_INTEGRATION_TIME
    SYSTEM_MAX_INTEGRATION_TIME_PARAM,             // SYSTEM_MAX_INTEGRATION_TIME
    SYSTEM_SENSOR_ANALOG_GAIN_PARAM,               // SYSTEM_SENSOR_ANALOG_GAIN
    SYSTEM_MAX_SENSOR_ANALOG_GAIN_PARAM,           // SYSTEM_MAX_SENSOR_ANALOG_GAIN
    SYSTEM_SENSOR_DIGITAL_GAIN_PARAM,              // SYSTEM_SENSOR_DIGITAL_GAIN
    SYSTEM_MAX_SENSOR_DIGITAL_GAIN_PARAM,          // SYSTEM_MAX_SENSOR_DIGITAL_GAIN
    SYSTEM_ISP_DIGITAL_GAIN_PARAM,                 // SYSTEM_ISP_DIGITAL_GAIN
    SYSTEM_MAX_ISP_DIGITAL_GAIN_PARAM,             // SYSTEM_MAX_ISP_DIGITAL_GAIN
    SYSTEM_DIRECTIONAL_SHARPENING_TARGET_PARAM,    // SYSTEM_DIRECTIONAL_SHARPENING_TARGET
    SYSTEM_UN_DIRECTIONAL_SHARPENING_TARGET_PARAM, // SYSTEM_UN_DIRECTIONAL_SHARPENING_TARGET
    SYSTEM_IRIDIX_STRENGTH_TARGET_PARAM,           // SYSTEM_IRIDIX_STRENGTH_TARGET
    SYSTEM_MAXIMUM_IRIDIX_STRENGTH_PARAM,          // SYSTEM_MAXIMUM_IRIDIX_STRENGTH
    SYSTEM_MINIMUM_IRIDIX_STRENGTH_PARAM,          // SYSTEM_MINIMUM_IRIDIX_STRENGTH
    SYSTEM_IRIDIX_DIGITAL_GAIN_PARAM,              // SYSTEM_IRIDIX_DIGITAL_GAIN
    SYSTEM_SINTER_THRESHOLD_TARGET_PARAM,          // SYSTEM_SINTER_THRESHOLD_TARGET
    SYSTEM_AWB_RED_GAIN_PARAM,                     // SYSTEM_AWB_RED_GAIN
    SYSTEM_AWB_BLUE_GAIN_PARAM,                    // SYSTEM_AWB_BLUE_GAIN
    SYSTEM_AWB_CCT_PARAM,                          // SYSTEM_AWB_CCT
    SYSTEM_SATURATION_TARGET_PARAM,                // SYSTEM_SATURATION_TARGET
    SYSTEM_ANTI_FLICKER_FREQUENCY_PARAM,           // SYSTEM_ANTI_FLICKER_FREQUENCY
    IMAGE_CROP_ENABLE_ID_PARAM,                    // IMAGE_CROP_ENABLE_ID
    IMAGE_CROP_WIDTH_ID_PARAM,                     // IMAGE_CROP_WIDTH_ID
    IMAGE_CROP_HEIGHT_ID_PARAM,                    // IMAGE_CROP_HEIGHT_ID
    IMAGE_CROP_XOFFSET_ID_PARAM,                   // IMAGE_CROP_XOFFSET_ID
    IMAGE_CROP_YOFFSET_ID_PARAM,                   // IMAGE_CROP_YOFFSET_ID
    OUTPUT_AXI1_FORMAT_ID_PARAM,                   // OUTPUT_AXI1_FORMAT_ID
    OUTPUT_AXI2_FORMAT_ID_PARAM,                   // OUTPUT_AXI2_FORMAT_ID
    OUTPUT_AXI3_FORMAT_ID_PARAM,                   // OUTPUT_AXI3_FORMAT_ID
    OUTPUT_FORMAT_MANUAL_CFG_APPLY_ID_PARAM,       // OUTPUT_FORMAT_MANUAL_CFG_APPLY_ID
    OUTPUT_FORMAT_ID_PARAM,                        // OUTPUT_FORMAT_ID
    REGISTERS_ADDRESS_ID_PARAM,                    // REGISTERS_ADDRESS_ID
    REGISTERS_SIZE_ID_PARAM,                       // REGISTERS_SIZE_ID
    REGISTERS_SOURCE_ID_PARAM,                     // REGISTERS_SOURCE_ID
    REGISTERS_VALUE_ID_PARAM,                      // REGISTERS_VALUE_ID
    STATUS_INFO_EXPOSURE_LOG2_ID_PARAM,            // STATUS_INFO_EXPOSURE_LOG2_ID
    STATUS_INFO_LDR_GAIN_LOG2_ID_PARAM,            // STATUS_INFO_LDR_GAIN_LOG2_ID
    STATUS_INFO_IRIDIX_CONTRAST_PARAM,             // STATUS_INFO_IRIDIX_CONTRAST
    STATUS_INFO_AE_HIST_MEAN_PARAM,                // STATUS_INFO_AE_HIST_MEAN
    STATUS_INFO_GAIN_ONES_ID_PARAM,                // STATUS_INFO_GAIN_ONES_ID
    STATUS_INFO_GAIN_LOG2_ID_PARAM,                // STATUS_INFO_GAIN_LOG2_ID
    STATUS_INFO_AWB_MIX_LIGHT_CONTRAST_PARAM,      // STATUS_INFO_AWB_MIX_LIGHT_CONTRAST
    ISP_MODULES_MANUAL_IRIDIX_PARAM,               // ISP_MODULES_MANUAL_IRIDIX
    ISP_MODULES_MANUAL_SINTER_PARAM,               // ISP_MODULES_MANUAL_SINTER
    ISP_MODULES_MANUAL_FRAME_STITCH_PARAM,         // ISP_MODULES_MANUAL_FRAME_STITCH
    ISP_MODULES_MANUAL_RAW_FRONTEND_PARAM,         // ISP_MODULES_MANUAL_RAW_FRONTEND
    ISP_MODULES_MANUAL_BLACK_LEVEL_PARAM,          // ISP_MODULES_MANUAL_BLACK_LEVEL
    ISP_MODULES_MANUAL_SHADING_PARAM,              // ISP_MODULES_MANUAL_SHADING
    ISP_MODULES_MANUAL_DEMOSAIC_PARAM,             // ISP_MODULES_MANUAL_DEMOSAIC
    ISP_MODULES_FORCE_BIST_MISMATCH_PARAM          // ISP_MODULES_FORCE_BIST_MISMATCH
};

// Translate command id to parameter id
uint32_t command_id_to_param_id( uint32_t command_id )
{
    if ( command_id > COMMAND_TO_PARAM_MAP_MAX_ID ) {
        return 0;
    } else {
        return command_to_param_map[command_id];
    }
}
